version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/code
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}
      - run:
          name: submodules
          command: git submodule init && git submodule update
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            export PIPENV_VENV_IN_PROJECT=~/code
            pipenv install
      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}
      - run:
          name: Generate Corresponding Proto classes
          command: |
            mkdir -p src/services
            python -m grpc_tools.protoc -I src/proto --python_out=src/services --grpc_python_out=src/services src/proto/covidsafe.proto
      - run:
          name: Check Linting
          command: pylint --rcfile tests/lint/pylintrc src

workflows:
  main:
    jobs:
      - build-and-test
