version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          key: deps
      - python/install-deps
      - save_cache:
          key: deps
          paths:
            - "/usr/local/bin"
      - run:
          name: pylint
          command: pylint --rcfile tests/lint/pylintrc src
      - run:
          name: proto
          command: python -m grpc_tools.protoc -I src/proto --python_out=. --grpc_python_out=. src/proto/covidsafe.proto

workflows:
  main:
    jobs:
      - build-and-test
